### ISSUE TITLE
Bug i think

### ISSUE THREAD

**Issue by Lordusin** [qbcore-framework/qb-policejob#121]
![Screenshot_2](https://user-images.githubusercontent.com/57770441/136054706-738bfa7d-2153-4b3f-8bcd-a6da605bd4bb.png)

where is E - Go on duty i think need to say E - Go off duty 

Sorry for bad English

**Comment by Boom1053** [comment]
No e just gone off duty is fine.

New notification system

**Comment by Lordusin** [comment]
Ok sir 
Thanks
