### ISSUE TITLE
[BUG] Always log in as ON DUTY?

### ISSUE THREAD

**Issue by Choppa25** [qbcore-framework/qb-policejob#132]
**Describe the bug**
Whenever I log in I'll always be on duty already. This **is not** just a "visual bug" regarding the /job command saying that I'm on duty when I'm not. 

**To Reproduce**
1. Go to qb-core/shared.lua and set police defaultduty = false.
2. Go to PD and clock off.
3. Leave the server, restart, whatever you want, join back. You're on duty again anyway.

**Expected behavior**
You should be off duty when joining back, especially after setting defaultduty = false.

**Screenshots**
n/a

**Questions (please complete the following information):**
 - When you last updated: core and police-job are up to date.
 - Are you using custom resource? which ones?: no?
 - Have you renamed `qb-` to something custom?: no

**Additional context**
n/a

**Comment by LV-Soft** [comment]
Check https://github.com/qbcore-framework/qb-core/pull/274
