### ISSUE TITLE
Remove objet 

### ISSUE THREAD

**Issue by Little-Poney** [qbcore-framework/qb-policejob#14]
On the qb-policejob file, it is impossible to remove an object placed on the ground. 

Error message:
script:qb-policejob > callback (@qp-radialmenu/client/main.lua:171)
script:qb-policejob > SCRIPT ERROR : @qb-policejob/client/objects.lua:107: attempt to compare nil with number

**Comment by GhzGarage** [comment]
Should be fixed with https://github.com/qbcore-framework/qb-policejob/commit/261ecb0815463e180a9733801baf2618717f591e
