### ISSUE TITLE
[BUG] location in phone MDT always sets to the same spot for 911p

### ISSUE THREAD

**Issue by lildiznick** [qbcore-framework/qb-policejob#143]
**Describe the bug**
When a player makes a 911p call, the blip on the map for the alert is correct, but when an officer clicks on the call in the MDT in the phone, it always places a blip on postal 570 (Map screenshot attached)

**To Reproduce**
1. Civ place a /911p call
2. Officer opens the MDT on the phone
3. Officer clicks alert in phone's MDT
4. Waypoint always set at the same location, not the location of the incident

**Expected behavior**
An accurate waypoint to be placed for /911p call location

**Screenshots**
![FiveM - Wee Woo Crew Public RP Server 10_21_2021 2_07_51 AM](https://user-images.githubusercontent.com/68559172/138229399-7d748bdb-2261-428b-93ed-c4318f9357e2.png)
![FiveM - Wee Woo Crew Public RP Server 10_21_2021 2_07_53 AM](https://user-images.githubusercontent.com/68559172/138229400-2142c2be-38c8-4dff-8a5c-72a7e6729b7a.png)

**Questions (please complete the following information):**
 - When you last updated: qb-policejob: tonight after commit message sent in discord
 - Are you using custom resource? which ones? The Garage's MDT, but this script is not applicable to this issue
 - Have you renamed `qb-` to something custom? No

**Additional context**
I have tried this with several players in several locations and have had the same result

**Comment by tony-stark-17** [comment]
That right there is the coord (0, 0, 0).
