### ISSUE TITLE
[unable to open mdt]

### ISSUE THREAD

**Issue by TheRedxQueen** [qbcore-framework/qb-policejob#169]
When I try to open the mdt using /mdt, no mdt populates and it breaks my chat box to where it freezes the dropdown onto my screen and I cannot get rid of it as shown in the image below:

![image](https://user-images.githubusercontent.com/90471209/141364958-19073ebc-abaa-4596-a658-b00a8be891cc.png)

I just updated the file today to the latest policejob. Using the qbus framework in full.

**Comment by GhzGarage** [comment]
There is no MDT

**Comment by TheRedxQueen** [comment]
might wanna change the commands list you have then

![image](https://user-images.githubusercontent.com/90471209/141370672-c01526a2-6cb0-4eaf-b39b-1a57cd904f8d.png)

**Comment by GhzGarage** [comment]
I will

**Comment by WEEZOOKARP** [comment]
> I will
when
