### ISSUE TITLE
police garage not loading vehicles

### ISSUE THREAD

**Issue by nggcasey** [qbcore-framework/qb-policejob#179]
When I open up the police garage, no vehicles show up despite having vehicles in the config.

Reverted to an older version of qb-policejob and no issues.

**Comment by yasmijn-vels** [comment]
replace this file and it will works

i have made a fix for it
https://we.tl/t-b98bPnoBrM

**Comment by BruhKein** [comment]
It seems that I having same issue. I manage to tweak it temporary but it definitely doesn’t work the way it suppose to. Is it possible to send me that file too please

**Comment by Maverick167** [comment]
> replace this file and it will works
> 
> i have made a fix for it https://we.tl/t-b98bPnoBrM

The link to your fix is expired. I'm having this issue with a fresh install of QB-Core. Does anyone happen to have the fix for this? The police garage is literally empty with no client or server errors.
