### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amantu-qbit** [qbcore-framework/qb-policejob#184]
**Describe the bug**
Robbery/Shot/Vehicle Theft fire don't send any alert to police

**To Reproduce**
1. Shot anywhere or Do robbery
2. Start Illegal activity.
3. Not sending any alert

**Expected behavior**
Should Send an alert to police

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] [Yesterday]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] [NO]
 - Have you renamed `qb-` to something custom? [e.g. yes/no] [NO]

**Additional context**

**Comment by OxGhali** [comment]
TriggerServerEvent('police:server:policeAlert', 'Bank Robbery')
use this function on your robbery script

**Comment by amantu-qbit** [comment]
> TriggerServerEvent('police:server:policeAlert', 'Bank Robbery') use this function on your robbery script

can you elaborate? like where?

**Comment by amantu-qbit** [comment]
> TriggerServerEvent('police:server:policeAlert', 'Bank Robbery') use this function on your robbery script

It's giving multiple notifications. As many police are there as much notification I'm getting

**Comment by daf4ever** [comment]
I also dont get alerts when gunshots are fired. Is there a fix for that? In which file would I have to put the: "TriggerServerEvent('police:server:policeAlert', 'Gun Shots)" ??

**Comment by daf4ever** [comment]
> I also dont get alerts when gunshots are fired. Is there a fix for that? In which file would I have to put the: "TriggerServerEvent('police:server:policeAlert', 'Gun Shots)" ??

I went to get another script that sends out notifications. So my problem is fixed now.
