### ISSUE TITLE
[BUG] Evidence 

### ISSUE THREAD

**Issue by mirrox1337** [qbcore-framework/qb-policejob#206]
**Describe the bug**
Stuck with cursor after trying to open a drawer

**To Reproduce**
1. Go to evidence stash
2. Open meny
3. Submiting a number (drawer)
4. Cursor gets stuck on screen with no error message

**Expected behavior**
Open the stash

**Questions (please complete the following information):**
 Freshbuild
 No
 No

**Comment by GhzGarage** [comment]
Update your input

**Comment by amantu-qbit** [comment]
@mirrox1337 Freshbuild without any error from my side

**Comment by MonkeyWhisper** [comment]
This was fixed when qb-input was updated.
