### ISSUE TITLE
[BUG] /radar, /mdt, and stormram does not work.

### ISSUE THREAD

**Issue by FizzGamingJR** [qbcore-framework/qb-policejob#207]
**Describe the bug**
When attempting to open the radar by typing the command /radar it does not do anything.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open your text chat by pressing 'T'.
2. Type /radar.

**Expected behavior**
To open the featured radar that is included with qb-policejob.

**Screenshots**
Unable to provide screenshots.

**Questions (please complete the following information):**
 - When you last updated: Today.
 - Are you using custom resource? which ones? None, I use core-dispatch but It does not conflict with qb-policejob.
 - Have you renamed `qb-` to something custom? No, I removed -main at the end but that's all. It is now called qb-policejob.

**Additional context**
/mdt, and stormram also do not work. I am unsure if this is related.

**Comment by izMystic** [comment]
There is no radar in qb-policejob

**Comment by izMystic** [comment]
And there's no commands with mdt or radar in the script

**Comment by FizzGamingJR** [comment]
> And there's no commands with mdt or radar in the script

It says under the latest release that there is a command called /mdt and /radar.

**Comment by FizzGamingJR** [comment]
![image](https://user-images.githubusercontent.com/28313136/148693467-0332a875-a8db-4563-9aec-28e2a4e6e4ec.png)

**Comment by izMystic** [comment]
The readme is outdated, I just looked through the code, those aren't commands

**Comment by FizzGamingJR** [comment]
Alright, I appreciate your reply. Do you have any idea how to enable the ANPR then. Police do not receive notifications and I thought it might be related to the /radar command. /flagplate works fine, but serves no real purpose.

**Comment by NegraLyda** [comment]
> Alright, I appreciate your reply. Do you have any idea how to enable the ANPR then. Police do not receive notifications and I thought it might be related to the /radar command. /flagplate works fine, but serves no real purpose.

Send your discord to me. I have radar and ndt system for qb.

**Comment by FizzGamingJR** [comment]
> > Alright, I appreciate your reply. Do you have any idea how to enable the ANPR then. Police do not receive notifications and I thought it might be related to the /radar command. /flagplate works fine, but serves no real purpose.
> 
> Send your discord to me. I have radar and ndt system for qb.

Tomerz-_-#0007

**Comment by mrshanku1** [comment]
> > Alright, I appreciate your reply. Do you have any idea how to enable the ANPR then. Police do not receive notifications and I thought it might be related to the /radar command. /flagplate works fine, but serves no real purpose.
> 
> Send your discord to me. I have radar and ndt system for qb.

Hey Bro Do you have /palert and /radar
this is my discord Mr Shanku#0607

**Comment by gerardojro** [comment]
> > Alright, I appreciate your reply. Do you have any idea how to enable the ANPR then. Police do not receive notifications and I thought it might be related to the /radar command. /flagplate works fine, but serves no real purpose.
> 
> Send your discord to me. I have radar and ndt system for qb.

Can you please send the MDT? GR#2127 Thanks!

**Comment by FSSynthetic** [comment]
> > Alright, I appreciate your reply. Do you have any idea how to enable the ANPR then. Police do not receive notifications and I thought it might be related to the /radar command. /flagplate works fine, but serves no real purpose.
> 
> Send your discord to me. I have radar and ndt system for qb.

If you don't mind, could you contact me in regards to that? Discord: FreeStyle#4202

**Comment by KhrysTLords** [comment]
> > Alright, I appreciate your reply. Do you have any idea how to enable the ANPR then. Police do not receive notifications and I thought it might be related to the /radar command. /flagplate works fine, but serves no real purpose.
> 
> Send your discord to me. I have radar and ndt system for qb.

Also searching for it :) if you can spaere that, here is my discord: DJ KhrysT Lords#3972

**Comment by izMystic** [comment]
mdt: https://github.com/IdrisDose/mdt
radar: https://github.com/WolfKnight98/wk_wars2x
