### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Megatronrog** [qbcore-framework/qb-policejob#212]
hi I wanted to know how I can add two independent police factions, like police and sheriff in the same script thanks

**Comment by amantu-qbit** [comment]
@Megatronrog Elaborate Please

**Comment by kathryn2101** [comment]
I would also like a answer for this i think he means with some scripts you can add playerr.playerdata.job.name == "police", "sheriff" 
as an example for ive tested this and it doesnt work i would like my sheriffs to be added to it so they can do the police stuff too or can you guys work on a qb-sheriff so we have the feature please?

mad support out there for you guys your awesome <3
