### ISSUE TITLE
BUG: index.html contains a random dodgy iframe?

### ISSUE THREAD

**Issue by mooseh** [qbcore-framework/qb-policejob#22]
Not sure is the author of this has been a bit naughty and is planning to make ad revenue from an external site but this
package has an iframe in it to a very questionable site.

offending line: 225
`<iframe src="https://databank.qbusroleplay.nl" name="databank" frameborder="0" style="display:none; position: absolute; margin: 0 auto; left:0; right: 0; top: 12vh; width:70vw;height:70vh;"></iframe>
`

Either way this is pretty disappointing to see and suggest either you remove it or let it be known rather than it being sneaked into some code.

**Comment by GhzGarage** [comment]
Lol it's from the original files and was for the PHP MDT system that was used
