### ISSUE TITLE
Hello, just a simple suggetion to see if it's possible[SUGGESTION]

### ISSUE THREAD

**Issue by Maureks** [qbcore-framework/qb-policejob#224]
**Is your feature request related to a problem? Please describe.**
no , no problem whatsoever

**Describe the feature you'd like**
A qb-target function for the police to cuff people , to save time going to radial menu or using the command /cuff

**Describe alternatives you've considered**
I have tried many ways in qb-target , but i can't seem to make it work 

Like this in Config.Global.Players : 

    ["targetmodel1"] = {
        models = {"mp_m_freemode_01","mp_f_freemode_01"},
        options = {
            {
 			    type = "client",
                event = "police:client:CuffPlayerSoft",
                icon = "fas fa-hands",
                label = "Cuff",
                job = "police",
            },
        },
        distance = 2.5,
    },

**Additional context**
I've tried also with:

 type = "command"
event = "cuff"

but it didn't work either.

Am I doing something wrong? Is something missing? What can I do?

Thanks in advance, and sorry for the bad english!

**Comment by MonkeyWhisper** [comment]
This is more of a snippet, if you want to make a PR for it with an option to enable/disable on the config, that's fine. Make a PR.
