### ISSUE TITLE
[BUG] Emergency Button doesn't work, no errors.

### ISSUE THREAD

**Issue by Duguayster** [qbcore-framework/qb-policejob#226]
**Describe the bug**
Simple, when on duty as Police Job, when using the Emergency Button it doesn't work or alert other medics of anything. No errors in console or server log.

**To Reproduce**
1. Go on DUTY as Police Job
2. Have another person go on duty.
3. Try the Emergency button via the F1 > Work menu.

**Expected behavior**
You are expected to send an alert to your fellow officers along with a marker on the map.

**Screenshots**
Self explanatory.

**Questions (please complete the following information):**
 - Just looking forward to seeing this work, I haven't seen this work since I first started using QBCore a few months ago.

**Additional context**
I have no idea how to fix it or get it working. I'm just looking forward to everything working! Thank you guys!!! Much love for QBCORE!!!!!!! <3<3<3

**Comment by MonkeyWhisper** [comment]
This is fixed, I tried it
