### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by gerardojro** [qbcore-framework/qb-policejob#230]
**Is your feature request related to a problem? Please describe.** Request
A clear and concise description of what the problem is.

**Describe the feature you'd like**
A clear and concise description of what you want to happen. and with as much detail as possible how it would function in your opinion. Please try to keep it unique.

I don’t know if this is implemented on the MDT (that we no longer have) but it would be nice to have a list of fines available either on the MDT or RadialMenu

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered for people to have in mind just in case the main idea isn't liked but a derivative is.

**Additional context**

**Comment by MonkeyWhisper** [comment]
Use an MDT for that. Currently the framework does not come with one.
