### ISSUE TITLE
[BUG] Locales not working properly

### ISSUE THREAD

**Issue by KingRyuShin** [qbcore-framework/qb-policejob#235]
The local itself work, but showing a value inside the sentence doesn't work, it will show %{lastname} insted of the actual character last name

also this function does not work

> RegisterNetEvent('police:client:CheckStatus', function()
>     QBCore.Functions.GetPlayerData(function(PlayerData)
>         if PlayerData.job.name == "police" then
>             local player, distance = GetClosestPlayer()
>             if player ~= -1 and distance < 5.0 then
>                 local playerId = GetPlayerServerId(player)
>                 QBCore.Functions.TriggerCallback('police:GetPlayerStatus', function(result)
>                     if result then
>                         for k, v in pairs(result) do
>                             QBCore.Functions.Notify(''..v..'')
>                         end
>                     end
>                 end, playerId)
>             else
>                 QBCore.Functions.Notify(Lang:t("error.none_nearby"), "error")
>             end
>         end
>     end)
> end)

**Comment by TotoyMolaSalonga** [comment]
Same

**Comment by ItsANoBrainer** [comment]
Update your core and policejob, should be working fine now.
