### ISSUE TITLE
[BUG] Removeankle

### ISSUE THREAD

**Issue by Terranzin** [qbcore-framework/qb-policejob#239]
**Describe the bug**
The script with putting on a ankle on a player works great. Though, when you try to take them off with /removeankle it just refreshes where the target is at on the map, and they dont get removed at all. Player has relogged and used the /removeankle serveral times but it stays on no matter what.

**Comment by MonkeyWhisper** [comment]
Unable to duplicate, it works fine for me.

**Comment by P4R4NORM4L** [comment]
> Unable to duplicate, it works fine for me.

Try changing Neck accessories and see if it tells you that you can't change your clothing because of the anklet. I was having the same issue as terranzin

**Comment by FjamZoo** [comment]
Has this issue been fixed?

**Comment by FjamZoo** [comment]
Issue seems to be fixed.
