### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by UnknownPlay3r** [qbcore-framework/qb-policejob#240]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to 'locker room in police station '
2. Click on 'E View Clothing  '
3. Use this item 'Select any police clothing  and confirm' (item's name from shared.lua if applicable)
4. Nothing happens
![Untitled](https://user-images.githubusercontent.com/98692751/151699062-2991bba2-30d9-44e9-81cf-fca5acbc2e74.png)

Nothing happens, is this a known issue and sorry if this have come up before.

Thanks for anyones help.

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by MonkeyWhisper** [comment]
Correct, that's not free mode.
