### ISSUE TITLE
/mdt

### ISSUE THREAD

**Issue by XxTeamslayer8xX** [qbcore-framework/qb-policejob#241]
**Describe the bug**
When trying to access the /mdt feature that is listed in functions it's not opening anything up or not getting any errors

**To Reproduce**
type in /mdt

**Expected behavior**
For a MDT to open

**Questions (please complete the following information):**
 - When you last updated: Couple weeks ago
 - Are you using custom resource? which ones? qb-target
 - Have you renamed `qb-` to something custom? no

**Additional context**
Not sure if I'm supposed to use a different mdt or if this one comes with one.

**Comment by adityagavand** [comment]
do u have mdt resourse?

**Comment by WEEZOOKARP** [comment]
the readme is way out of date the actual mdt from the script is the one in the phone and the command does nothing

**Comment by XxTeamslayer8xX** [comment]
Ok thanks for the response. Is there a simple MDT out here that I can use
other than the phone?

**Comment by WEEZOOKARP** [comment]
i think kakarot has one

**Comment by MonkeyWhisper** [comment]
https://github.com/Project-Sloth/qb-mdt  - this MDT is work in progress.

https://github.com/GhzGarage/mdt - This MDT is ready to use.
