### ISSUE TITLE
[BUG] Police Impound location deletes vehicle.

### ISSUE THREAD

**Issue by MulGirtab** [qbcore-framework/qb-policejob#247]
When you go to the police impound as police and attempt to impound the vheicle using the "E" button it will delete the vehicle but it will not update the database to reflect it was impounded. The state still shows 0 "Out" and not 2 "Impound"

**To Reproduce**
1. Go to the police impound marker while onduty as police.
2. Hit "E" to impound vehicle.
3. Vehicle will delete but not show up as impounded.

`CreateThread(function()
    Wait(1000)
    local headerDrawn = false

    while true do
        local sleep = 2000
        if LocalPlayer.state.isLoggedIn and PlayerJob.name == "police" then
            local pos = GetEntityCoords(PlayerPedId())
            for k, v in pairs(Config.Locations["impound"]) do
                if #(pos - vector3(v.x, v.y, v.z)) < 7.5 then
                    if onDuty then
                        sleep = 5
                        DrawMarker(2, v.x, v.y, v.z, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.2, 0.15, 200, 0, 0, 222, false, false, false, true, false, false, false)
                        if #(pos - vector3(v.x, v.y, v.z)) <= 1.5 then
                            if IsPedInAnyVehicle(PlayerPedId(), false) then
                                DrawText3D(v.x, v.y, v.z, Lang:t('info.impound_veh'))
                            else
                                if not headerDrawn then
                                    headerDrawn = true
                                    exports['qb-menu']:showHeader({
                                        {
                                            header = Lang:t('menu.pol_impound'),
                                            params = {
                                                event = 'police:client:ImpoundMenuHeader',
                                                args = {
                                                    currentSelection = k,
                                                }
                                            }
                                        }
                                    })
                                end
                            end
                            if IsControlJustReleased(0, 38) then
				 QBCore.Functions.DeleteVehicle(GetVehiclePedIsIn(PlayerPedId()))   --<---- deletes vehicle but does not impound.
                            end
                        else
                            if headerDrawn then
                                headerDrawn = false
                                exports['qb-menu']:closeMenu()
                            end
                        end
                    end
                end
            end
        end
        Wait(sleep)
    end
end)`

This should update the database to show that it is in the police impound and when you look in the police impound it should show up.

 - When you last updated: 2/22/2021
 - Are you using custom resource? no
 - Have you renamed `qb-` to something custom? no

No errors are given.

**Comment by MonkeyWhisper** [comment]
To impound cars, you would do /impound as police

**Comment by MulGirtab** [comment]
I am aware of that. That's not the feature with the issue. The issue is if you take the car to the impound location and use the E button to impound it does not update the database to set the status to the impound.

**Comment by P4R4NORM4L** [comment]
Yeah I have the same issue. Even the /impound function does not store the vehicle for me

**Comment by FjamZoo** [comment]
This issue should of been resolved please update to latest and let me know if you still experience any issue

**Comment by XxDeezixX** [comment]
im having a problem we cant see anything in impound
