### ISSUE TITLE
[BUG] Script triggers non-existing event

### ISSUE THREAD

**Issue by JonasDev99** [qbcore-framework/qb-policejob#254]
**Describe the bug**
I found this event:  'qb-policealerts:client:AddPoliceAlert' and I have searched the whole qbcore org on github but no piece of code that listens to this event.

**Expected behavior**
Should this be qb-phone:client:AddPoliceAlert ?

**Screenshots**
![image](https://user-images.githubusercontent.com/25738474/153812752-aa310268-3e95-4fa8-9f88-982c921032cf.png)

**Questions (please complete the following information):**
 - When you last updated: last week
 - Are you using custom resource? which ones? tons but no qb-policealerts
 - Have you renamed `qb-` to something custom? no

**Comment by MonkeyWhisper** [comment]
That code is still there from old QBCore, we are still cleaning up. 

You may replace them for your own triggers for your dispatch.

**Comment by FjamZoo** [comment]
As stated above most of these have now been changed to a build in system, thank you for your issue.
