### ISSUE TITLE
[QUESTION] Evidences

### ISSUE THREAD

**Issue by Hopia-Island** [qbcore-framework/qb-policejob#255]
**Is your feature request related to a problem? Please describe.**
In the QB-POLICEJOB there is a way to have evidence: BLOOD / DNA / FINGERPRINT / CASING ect...
But none of them work or I don't know how to use them.

**Describe the feature you'd like**
Understand how it works, if I need an additional resource or if someone can help me understand.

**Comment by MonkeyWhisper** [comment]
Ask for help in QBCore discord.

**Comment by Hopia-Island** [comment]
For people :

The evidences are not in the policejob but like the jewlery rob script you have 5% chances to drop blood when brake glass or find fingerprint on glass so the script use the evidences ressource of policejob for blood drop when someone get shoot it's in ambulance job.
