### ISSUE TITLE
police garage not saving cars

### ISSUE THREAD

**Issue by Drakoumelis** [qbcore-framework/qb-policejob#258]
Whenever i get a car out of the menu i cant save it and it says that its not mine. if i try to just "park it" it works but i cant save it as my car like in  a normal garage.

**Comment by Drakoumelis** [comment]
i made one using a template from the luxury shop but after the made, the luxury shop shows up errors and the police shop just doesnt work

**Comment by izMystic** [comment]
you probably have a syntax error in the config

**Comment by SmithyPD** [comment]
you have to add vehicles into the core shared files, for them to be ownable and work in dealerships.
