### ISSUE TITLE
[BUG] store the player car in the garage police

### ISSUE THREAD

**Issue by z0nzjn123** [qbcore-framework/qb-policejob#261]
I discovered that when I put the player's car in the garage, it gets lost and can't be found anymore.
Sorry for my bad English

**Comment by z0nzjn123** [comment]
To solve the above problem, first add this function to qb-garage as follows:
https://github.com/qbcore-framework/qb-garages/pull/146
and modify it as follows:
https://github.com/qbcore-framework/qb-policejob/pull/262

**Comment by FjamZoo** [comment]
This issue has been fixed already, thank you for reporting.
