### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tyler4435** [qbcore-framework/qb-policejob#263]
i do not know how to add a player to be a cop
and be able for them to go on duty

**Comment by txdaniel55** [comment]
/setjob [playerid] [jobname] [grade]

You can find the playerid in the phone or typing /id.

So for example if you want to make player id 1 chief?

/setjob 1 police 4

**Comment by tyler4435** [comment]
ok how do i set up cq-admin menu in the server cfg

**Comment by tyler4435** [comment]
@txdaniel55 ^ how do i do it useing steam hex in cfg?

**Comment by IdrisDose** [comment]
cq-admin you have to ask the author.
