### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ShomyTKD** [qbcore-framework/qb-policejob#266]
**Describe the bug**
You can see other people's police blips even if you go off duty. It appears like they don't see your blip though.

**To Reproduce**
1. You and someone else should go on duty.
2. You should go now off duty.
3. Your friend should go off duty then.
4. Your friend won't see your blip, but you will still see his even though you are off duty.

**Expected behavior**
You shouldn't be able to see other people blips when off duty.

**Questions (please complete the following information):**
 - When you last updated: Today
 - Are you using custom resource? No
 - Have you renamed `qb-` to something custom? No

**Comment by FjamZoo** [comment]
This issue has been fixed please reopen the issue if it seems to be happening again.

Thank you for helping identifying the issues within this resouce.
