### ISSUE TITLE
[SUGGESTION] Configurable disable player blips(EMT\POLICE)

### ISSUE THREAD

**Issue by Jerrys-C** [qbcore-framework/qb-policejob#271]
**Is your feature request related to a problem? Please describe.**
When the player uses the multi-role menu to log in, if he first selects the police role, and then selects another professional role after logging out, such as taxi, his police player blips still exists,

**Describe the feature you'd like**
I wish it was possible to disable all EMT\Police's player blips via config or command

**Comment by bedrockmasterbg** [comment]
**blips are available only for upper ranks like admin,god*

**Comment by zwkf** [comment]
Closing this due to the age of the ticket. If it's still a problem feel free to reopen or raise another ticket. Thanks
