### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by itsAlphaMF** [qbcore-framework/qb-policejob#284]
I have tried to search to figure out how to do this, if I want to remove vanilla PD vehicles and add custom add-ons, how do I do that? I tried changing the name of "police" to my vehicle name, but it broke the spawner. I was thinking it might be in whitelisted config, but wasn't sure how to set that up. Any help would be appreciated!

**Comment by FjamZoo** [comment]
Change `Config.AuthorizedVehicles` to your liking with all the police cars custom or vanilla ones.
