### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Nick5M420** [qbcore-framework/qb-policejob#285]
**Describe the bug**
Every so often i get this crash thru the city i dont know what causes it figured id inquire here

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/95560411/161167975-73d69871-34fa-4cec-87b9-bd87cde0a421.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by OneMoreDilive** [comment]
Your server is under DDOS attack

**Comment by FjamZoo** [comment]
This is not an issue regarding this resource this is because your server is getting more traffic than it could handle, please update your Zap hosting vps using the Code QBCore for 10% off

**Comment by trclassic92** [comment]
![image](https://user-images.githubusercontent.com/82931913/173499347-d2b392fb-a37f-4953-84e3-42df83b639d9.png)
