### ISSUE TITLE
[BUG] You can impound podium vehicles from the qb-vehicleshop

### ISSUE THREAD

**Issue by Rayzer567** [qbcore-framework/qb-policejob#286]
**Describe the bug**
You can impound podium vehicles from the qb-vehicleshop

**To Reproduce**
1. Go to the podium vehicles (qb-vehicleshop)
2. You need to work as the police
3. Type /impound
4. And they are gone

**Expected behavior**
I didn't expect the podium vehicles to disappear

**Screenshots**
https://streamable.com/sk8jid
Here is a link to the video because the file is too big for github.

**Questions (please complete the following information):**
 - When you last updated: I did a fresh install with recipe yesterday.
 - Are you using custom resource? which ones? No.
 - Have you renamed `qb-` to something custom? No.

**Additional context**
You can impound podium vehicles from the qb-vehicleshop

**Comment by bedrockmasterbg** [comment]
*so this is possible because if for example you owe a fine or some property taxes to  the "city" police can impound the vehicles

**Comment by GodyFromDiscord** [comment]
I wasn't able to reproduce this on a fresh build;

https://medal.tv/games/gta-v/clips/WpegHtwgd7pnr/d1337fafxPlN?invite=cr-MSw4aUEsNjI2NTgyMSw

**Comment by Rayzer567** [comment]
> I wasn't able to reproduce this on a fresh build;
> 
> https://medal.tv/games/gta-v/clips/WpegHtwgd7pnr/d1337fafxPlN?invite=cr-MSw4aUEsNjI2NTgyMSw

Bro this was literally 1 year ago of course you cant do it now

**Comment by GodyFromDiscord** [comment]
> > I wasn't able to reproduce this on a fresh build;
> > https://medal.tv/games/gta-v/clips/WpegHtwgd7pnr/d1337fafxPlN?invite=cr-MSw4aUEsNjI2NTgyMSw
> 
> Bro this was literally 1 year ago of course you cant do it now

Dunno what's up with your attitude lmao, aint my fault issues aren't being closed
