### ISSUE TITLE
[BUG] players with high ping not being able to rob

### ISSUE THREAD

**Issue by Monkey1995** [qbcore-framework/qb-policejob#292]
**Describe the bug**
When a player with high ping/pl tries to rob a player that is dead nothing happens, only when the person dead on the floor puts there hands up it then let's the person with high ping rob them.

**To Reproduce**
1. Kill player with low/normall ping 10-40 ish ping
2. Player that has 100+ ping try to rob the first player when completly dead

**Expected behavior**
Player with high ping should be able to rob the person on the floor if dead fully, but only works when hands are up

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week
 - a couple of days ago
 - 
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - I'm using a few but in a fresh server install this still happens 
 - 
 - Have you renamed `qb-` to something custom? [e.g. yes/no]
 - no

**Additional context**
If the dead player where to put there hands up when on the ground complelty dead it will let the player with bad ping rob but if they dont they cant rob them, I've tried this the opposite way around and the person with good ping can rob a dead person if they have the hands down or up? 

I would be very grateful for a fix for this issue. Thanks in advance

**Comment by FjamZoo** [comment]
This issue has been fixed Thanks for the report.
