### ISSUE TITLE
[BUG] - Changing police cars

### ISSUE THREAD

**Issue by Hxdc11** [qbcore-framework/qb-policejob#293]
Can someone point me to the right direction on where can I change the default police car being provided? 

I tried to look in qb-policejob but it seems that there's none? Or I'm just missing something. 

Thank you!

**Comment by jnccloud** [comment]
Police cars are handled in config.lua, but if you want to change the 3D models then you will need to look into FiveM replacement/add-on cars.

**Comment by FjamZoo** [comment]
Issue has been handled by the above comment.
