### ISSUE TITLE
Police garage cars accessible from non police users

### ISSUE THREAD

**Issue by Progamerboys** [qbcore-framework/qb-policejob#302]
Everey one can take  car from police garage cars even if we are not in police job .

**Comment by TomTheDark** [comment]
The same

**Comment by L1quidSn4ke** [comment]
Is the police the only one? Check all job/gang garages.

**Comment by L1quidSn4ke** [comment]
Is the police the only one? Check all job/gang garages.

**Comment by zwkf** [comment]
Is this still an issue?

**Comment by GodyFromDiscord** [comment]
> Is this still an issue?

I have just tested this on a fresh build and I cannot replicate it
