### ISSUE TITLE
[BUG] uncuff_player Locale Missing

### ISSUE THREAD

**Issue by ConstantDevelopment** [qbcore-framework/qb-policejob#305]
**Describe the bug**
 There is a Locale missing for 'uncuff_player'

**To Reproduce**
1. Go to locale/* and search 'uncuff_player' within "commands" (commands.uncuff_player)

**Expected behavior**
 Set Locale being 
uncuff_player = 'UnCuff Player (Police Only)',

**Comment by itsKline** [comment]
There is a locale for uncuff. 

uncuffed = 'You have been uncuffed'
