### ISSUE TITLE
[BUG] When I take out any vehicle from Police Garage its throwing a Error ! And I didn't get Vehicle Key 

### ISSUE THREAD

**Issue by subhampro** [qbcore-framework/qb-policejob#308]
**Describe the bug**
When I take out any vehicle from Police Garage its throwing a Error ! And I didn't get Vehicle Key 

**To Reproduce**
1. Go to '...' PD Garage 
2. Click on '....' Police GARAGE
3. Select any Vehicle

**Expected behavior**
Vehicle spawned and I didn't get Vehicle Key 

**Screenshots**
![image](https://user-images.githubusercontent.com/33375250/166147304-44e8ec28-e5f1-4084-8f44-26594e217566.png)

**Questions (please complete the following information):**
 - When you last updated: Today !
 - Are you using custom resource? which ones?  no
 - Have you renamed `qb-` to something custom? no]

**Additional context**

**Comment by Rovelt123** [comment]
I have the same issue... Do you have a fix? :D

**Comment by GodyFromDiscord** [comment]
I cannot seem to reproduce this

**Comment by AnishBplayz** [comment]
Try checking your Config.Caritems table in config.lua it isn’t set right

**Comment by AnishBplayz** [comment]
Also have you changed your fuel script in the client side ?
