### ISSUE TITLE
[BUG] Armory

### ISSUE THREAD

**Issue by GhostLegionRP** [qbcore-framework/qb-policejob#314]
Once you move the Armory, the blip to open it doesn't always show up. You have to try a few times until you see it.

`    ["armory"] = {
        [1] = vector3(485.52, -1006.04, 25.73),
    },`
![no_blip](https://user-images.githubusercontent.com/100316482/170192356-b6d9d83b-bc1a-49f6-9821-c85c4a24ce03.PNG)

**Comment by FjamZoo** [comment]
This has been fixed please update.
