### ISSUE TITLE
Vehicles are receiving extras that I set to False in config file[BUG]

### ISSUE THREAD

**Issue by Flying-Turtles2** [qbcore-framework/qb-policejob#315]
**Describe the bug**
I have set my config with which Extras I do and do not want to spawn on the vehicles and instead the vehicles are spawning with every available extra.

**To Reproduce**
1. Add custom police vehicle with extras
2. Set extras you don't want to false in config file
3. launch server and pull out the vehicle

**Expected behavior**
Only extras set to True should be applied to the vehicle

**Code snippet from my config**
    ["fsv11vic"] = { --- Model name
        ["extras"] = {
            ["1"] = true, -- LightBar
            ["2"] = false, -- Takedowns
            ["3"] = false, -- Visor Lights
            ["4"] = true, -- Pushbar
            ["5"] = true, -- nothing
            ["6"] = true, -- Spotlight open
            ["7"] = false, -- Spotlight closed
            ["8"] = true, -- Trunk antenna
            ["9"] = true, -- Roof Antenna
            ["10"] = false, --ALPR Trunk
            ["11"] = false, -- ALPR Pushbar
            ["12"] = true, -- Running Lights
            ["13"] = true, -- nothing
        },
		["livery"] = 1,
    },

**Questions (please complete the following information):**
 - When you last updated: Today - 5/25/22
 - Are you using custom resource? which ones? (https://www.lcpdfr.com/downloads/gta5mods/vehiclemodels/38723-non-elsfivem-ready-2022-federal-signal-valor-pack/)
 - Have you renamed `qb-` to something custom? No

**Additional context**

**Comment by ItsVinnyX** [comment]
Can confirm. Does the same exact thing on my server. Looking into fixing this.

**Comment by Flying-Turtles2** [comment]
> 

Yeah I'd love to see how you fixed it

**Comment by Xodus989** [comment]
Only have the extras that you want to be true. the = true/false means nothing for some reason. See below for how to do it.

`
["fsv11vic"] = { --- Model name
["extras"] = {
["1"] = true, -- LightBar
["4"] = true, -- Pushbar
["5"] = true, -- nothing
["6"] = true, -- Spotlight open
["8"] = true, -- Trunk antenna
["9"] = true, -- Roof Antenna
["12"] = true, -- Running Lights
["13"] = true, -- nothing
},
["livery"] = 1,
},
`
