### ISSUE TITLE
[BUG] Cant access Armory

### ISSUE THREAD

**Issue by GhostLegionRP** [qbcore-framework/qb-policejob#316]
![police](https://user-images.githubusercontent.com/100316482/170243415-40a8f3d4-8a68-4acd-b5c6-2320dfcf2119.PNG)

since last update

**Comment by FjamZoo** [comment]
Are you on latest update and has this been resolved?

**Comment by GhostLegionRP** [comment]
> Are you on latest update and has this been resolved?

Is solved
