### ISSUE TITLE
[SUGGESTION] Fine menu (like Taxi Job Invoice)

### ISSUE THREAD

**Issue by bedrockmasterbg** [qbcore-framework/qb-policejob#317]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**
We want **menu for fine like the taxi job has /invoice**

**Describe alternatives you've considered**
so probably we can takes the fines by bank but if its possible make it to increase the police society account money

**Additional context**
DO IT FASTER cause

**Comment by i-kulgu** [comment]
This is already fixed. Look in #434
