### ISSUE TITLE
Allow `Config.PoliceHelicopter` to take a table, or a single heli

### ISSUE THREAD

**Issue by nggcasey** [qbcore-framework/qb-policejob#320]
**Describe the feature you'd like**

Change the config options for the Police helicopter from this:

Config.PoliceHelicopter = "POLMAV"

To something like this:

Config.PoliceHelicopter = {
    [1] = {
        model = "polmav",
        authorisedJobGrades = {2, 3, 4},
    },

    [2] = {
        model = "maverick",
        authorisedJobGrades = {3, 4},
    }
}

**Comment by jnccloud** [comment]
Note that this will require updating the camera as well, to check if the heli has that setting enabled. ie: `camEnabled = true`
