### ISSUE TITLE
`/escort` not possible on downed user

### ISSUE THREAD

**Issue by HIJINX0** [qbcore-framework/qb-policejob#322]
**Describe the bug**

Basically, when you go down and `/escort` someone and try going through `F1` menu, citizen, interaction, put in the vehicle you get this message "Civilian isn't cuffed or dead" but we are in a downed state. This happens to my players on the server not running the same CFX account.

**To Reproduce**
• Get shot or knocked out to go into the downed state.
• EMS /escort the player.
• Take the player to an ambulance.
• EMS presses F1 navigates to Citizen, Interaction, Put in vehicle.
• Prompt comes up saying Civilian isn't cuffed or dead.

**Expected behavior**
 To be able to put players into a vehicle in the first downed state not having to wait till they bleed out.

**Screenshots**
https://www.youtube.com/watch?v=ZK-W74iS-98

**Questions (please complete the following information):**
 - Last Updated: Few days ago, however, this has been a persistent issue for months, I have only just got around to reporting it.
 - Have you renamed `qb-` to something custom? [e.g. yes/no] NO

**Comment by bedrockmasterbg** [comment]
well did you tried the default ambulance cause every vehicle has different dimensions ?

**Comment by FjamZoo** [comment]
try to update your script as I could not replicate the issue

**Comment by ChickenDipper1** [comment]
This is the way it works for me too currently, only way to put someone in a vehicle as EMS is for the player not to be in last stand, but "fully dead" so just put a quick bullet in their head and you will be able too (might break RP rules).
