### ISSUE TITLE
[HELP]Add grades

### ISSUE THREAD

**Issue by CoZmoTheGod** [qbcore-framework/qb-policejob#325]
How do I make more grades? I want to add more ranks to my police job so how do I add custom ones with custom rank names?

**Comment by TheRealCasiv2** [comment]
look into the jobs.lua in the shared folder of qb-core

**Comment by CoZmoTheGod** [comment]
I couldn't find anything in job.lua, can you point me to specific line?

**Comment by FjamZoo** [comment]
Hey there, this is not a policejob specific issue please head over to qb-core/shared/jobs.lua and find the policejob and add as many grades as you wish.

I will be closing this issues as this is not a Policejob specific issue, if you need more help then please join our discord and im sure someone will point you in the right direction.
