### ISSUE TITLE
Police Radar

### ISSUE THREAD

**Issue by CrypticOG** [qbcore-framework/qb-policejob#33]
The police radar will not appear for me no matter what vehicle I'm in. I have tried the default GTA police vehicles and also my own addon vehicles and it does not appear.

**Comment by Tajemniaczek** [comment]
/radar...

**Comment by CrypticOG** [comment]
@Tajemniaczek 
Lmao I've tried that multiple times on multiple vehicles that's why I opened  an issue on github.

**Comment by GhzGarage** [comment]
Must use your own radar and trigger
