### ISSUE TITLE
Police job garage cant access cars error pops up. 

### ISSUE THREAD

**Issue by NOFace90** [qbcore-framework/qb-policejob#331]
**Describe the bug**
when you try to get a police car out the garage it doesnt show ant options and give this error
**To Reproduce**
1. Go to '...' police garage 
2. Click on '....' police grarge and clike on it 
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**
to have a police car option menu and spawn the car 
**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: today 
 - Are you using custom resource? which ones? no
 - Have you renamed `qb-` to something custom? no
![Screenshot (20)](https://user-images.githubusercontent.com/107782646/174505910-d22f2f61-c74b-4dca-ae71-16a24e518e6a.png)

**Additional context**

**Comment by Unkn0wnD3v** [comment]
You have to set vehicles for each grade, Grade 4 won't use anything lower as you'd expect it to do so.

**Comment by Txc32** [comment]
same

**Comment by GodyFromDiscord** [comment]
I cannot reproduce this, you must have set something up wrong
