### ISSUE TITLE
[SUGGESTION] Add other departments

### ISSUE THREAD

**Issue by TankinTom** [qbcore-framework/qb-policejob#337]
**Is your feature request related to a problem? Please describe.**
Negative

**Describe the feature you'd like**
By default, the police job is for LSPD (As far as I know) Is there a way to add other departments Like BCSO and SAST?

**Describe alternatives you've considered**
I thought about adding the ranks to the boss menu, and having multiple places, but that seemed like a terrible idea

**Comment by sinphoenix** [comment]
create them as jobs, COPY the Police section under Shared > jobs.lua. Then just edit to your liking. Make sure to go to Policejob and where it has job listed as police to add those in there as well.. 

Or, we leave police job but have different departments within one. So we have State, BCSO, LSPD, DOC, and GW all under Police job

Hope that makes sense

**Comment by TankinTom** [comment]
So with the first option, we tried that, and with how it's coded, whatever loads last is the only actual police, so you'd have to go back and edit imports and exports to include the other departments. We did that with some success, about 90%, but then decided to just edit the police ranks, go back to defaults, and change ranks to be GS01-GS08. GS meaning Government service, and each department had the same number of ranks.

**Comment by sinphoenix** [comment]
that would be a good alternative.

**Comment by i-kulgu** [comment]
See #434  for multijob setup.

**Comment by Dbowen99** [comment]
Is there a video on how to do this trying to set up now

**Comment by TankinTom** [comment]
> 

We ended up switching to Wasabi advanced police job, and it fixed all of our issues.
