### ISSUE TITLE
[BUG] impound police can't be used

### ISSUE THREAD

**Issue by XLightDev** [qbcore-framework/qb-policejob#339]
impound police can't be used

When the police impound the vehicle, in the player_vehicles SQL matches the state it should be 2, but it doesn't change.

**Comment by nzkfc** [comment]
From what I can see, there is /depot and /impound, but both commands call for: police:client:ImpoundVehicle

Which is:
`RegisterNetEvent('police:client:ImpoundVehicle', function(fullImpound, price)
    local vehicle = QBCore.Functions.GetClosestVehicle()
    local bodyDamage = math.ceil(GetVehicleBodyHealth(vehicle))
    local engineDamage = math.ceil(GetVehicleEngineHealth(vehicle))
    local totalFuel = exports['ps-fuel']:GetFuel(vehicle)
    if vehicle ~= 0 and vehicle then
        local ped = PlayerPedId()
        local pos = GetEntityCoords(ped)
        local vehpos = GetEntityCoords(vehicle)
        if #(pos - vehpos) < 5.0 and not IsPedInAnyVehicle(ped) then
            local plate = QBCore.Functions.GetPlate(vehicle)
            TriggerServerEvent("police:server:Impound", plate, fullImpound, price, bodyDamage, engineDamage, totalFuel)
            QBCore.Functions.DeleteVehicle(vehicle)
        end
    end
end)`

and then that police:server:Impound is going to:
`RegisterNetEvent('police:server:Impound', function(plate, fullImpound, price, body, engine, fuel)
    local src = source
    price = price and price or 0
    if IsVehicleOwned(plate) then
        if not fullImpound then
            MySQL.query(
                'UPDATE player_vehicles SET state = ?, depotprice = ?, body = ?, engine = ?, fuel = ? WHERE plate = ?',
                {0, price, body, engine, fuel, plate})
            TriggerClientEvent('QBCore:Notify', src, Lang:t("info.vehicle_taken_depot", {price = price}))
        else
            MySQL.query(
                'UPDATE player_vehicles SET state = ?, body = ?, engine = ?, fuel = ? WHERE plate = ?',
                {2, body, engine, fuel, plate})
            TriggerClientEvent('QBCore:Notify', src, Lang:t("info.vehicle_seized"))
        end
    end
end)`

In there it's telling SQL to set state 0 or 2 (I assume 0 to send the car to depot when using /depot and then state 2 for impound when using /impound.

However i'm not sure what this fullImpound function is, so my brain tells me /impound and /depot needs different events but I assume thats what fullImpound is.

**Comment by EZIKEL1** [comment]
what do i do to fix it? the police impound is not working for me

**Comment by IIMKII** [comment]
same here
