### ISSUE TITLE
[BUG] Blood and Bullet Casings

### ISSUE THREAD

**Issue by Fuachi** [qbcore-framework/qb-policejob#340]
I haven't made any changes to the file, but the bullet casings and blood are not showing on the floor.
How can i fix it?

**Comment by nzkfc** [comment]
Also having the same issue.

**Comment by xnubil** [comment]
This error is related back to adding casings/blood/fingerprints into the table for flashlight to see.
[Casings[casingId]](https://github.com/qbcore-framework/qb-policejob/blob/d36c4c0b43556e7d9b9369682f2cd7570b220b73/client/evidence.lua#L152)

I modified the table insert to 
`Casings[#Casings+1] = {...}`
And the casing now populate for the flashlight to see
