### ISSUE TITLE
[BUG] Take Out Impound Error Coords

### ISSUE THREAD

**Issue by XLightDev** [qbcore-framework/qb-policejob#342]
Happened when I picked up an impounded car

![image](https://user-images.githubusercontent.com/108535266/177338852-1761bf06-42eb-499a-a2c7-678e2403e013.png)

**Comment by Galactuuus** [comment]
Did you try to change the config.lua and set the impound array to vector 3¿?
The GetEntityCoords return a vector3 and the impound in config.lua is a vector4.
