### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ckaysone380** [qbcore-framework/qb-policejob#346]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
1. Go to '.QB Police Job.'
2. Click on '.E.'
3. Use this item '.No Item, just spawns in helicopter’

**Expected behavior*
When on the police job, if you hit E a helicopter for LSPD spawns in, if in any other vehicle hitting E anywhere despawns the car and unsure why.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [Today]
 - Are you using custom resource? Fresh Install
 - Have you renamed `qb-` to something custom? [e.g. No]

**Comment by i-kulgu** [comment]
Already fixed in the latest version.
