### ISSUE TITLE
[BUG] Police Blips

### ISSUE THREAD

**Issue by Dani24HUN** [qbcore-framework/qb-policejob#347]
When i go off duty, my blip is still on, and never disappear

**Comment by Galactuuus** [comment]
Hi!, did you check you are really out off duty, can you go to your BBDD (database) and check if in the column job the json that is provided the value of "onduty" is set to false.

shoud be something like this - [https://imgur.com/a/X6VkFVP](url)

**Comment by Dani24HUN** [comment]
If i go offduty, the database only refresh it when i made a game restart or a logout.

**Comment by kokorog** [comment]
same
