### ISSUE TITLE
[BUG]  police onduty in game server

### ISSUE THREAD

**Issue by Jokrupappa** [qbcore-framework/qb-policejob#349]
How can I make sure that when the police come to the server, they will be on duty? help me

**Comment by amantu-qbit** [comment]
![image](https://user-images.githubusercontent.com/67361813/181095792-5d63a196-0d81-4410-8290-ae84ac1ed470.png)
QBShared.ForceJobDefaultDutyAtLogin = true
defaultDuty = true
