### ISSUE TITLE
[BUG] Add-On Police cars will not park

### ISSUE THREAD

**Issue by DeanoWtr** [qbcore-framework/qb-policejob#351]
**Describe the bug**
I have added a Police charger to my city and when i go to park it. First there is 2 spot to depot the car. I can put it in one and never retrieve it and the other one says its not authorized. I have added the model to the config and still nothing. On the (Hold Alt) Garage i can spawn vanilla cars only. 

Config: 
Config.AuthorizedVehicles = {
	-- Grade 0
	[0] = {
		["pdcharger"] = "Police Car 1",	
	},
	-- Grade 1
	[1] = {
		["pdcharger"] = "Police Car 1",
	},
	-- Grade 2
	[2] = {
		["pdcharger"] = "Police Car 1",		
	},
	-- Grade 3
	[3] = {
		["pdcharger"] = "Police Car 1",		
	},
	-- Grade 4
	[4] = {
		["pdcharger"] = "Police Car 1",		
	}
}

**Comment by i-kulgu** [comment]
You need to own the car first prior to storing it into the garage.
A car that you spawn from the policejob is not yours.
