### ISSUE TITLE
/depot not saving price to sql

### ISSUE THREAD

**Issue by CaptnSloth** [qbcore-framework/qb-policejob#36]
/depot [prije] not saving price to sql stays at a 0 value
![20210731013020_1](https://user-images.githubusercontent.com/88228689/127734124-f6aa813e-9908-42e7-ac83-2ed956bd623f.jpg)
![20210731013038_1](https://user-images.githubusercontent.com/88228689/127734125-7a8bda16-fcf7-4f7f-8b8c-e509b1b2270e.jpg)

**Comment by Developer-Bear** [comment]
New PR open with a fix, tested and working on my end. 

https://github.com/qbcore-framework/qb-policejob/pull/38

**Comment by CaptnSloth** [comment]
worked like a charm!

**Comment by Developer-Bear** [comment]
Thanks for the report! :)
