### ISSUE TITLE
[BUG] /radar don't work

### ISSUE THREAD

**Issue by Xeast7487** [qbcore-framework/qb-policejob#361]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
Get in a police car, tried /radar but nothing works

**Comment by Exyztence** [comment]
did u fix it? same issue here

**Comment by Mzori19** [comment]
i have the same issue!

**Comment by i-kulgu** [comment]
There is no /radar command. Radars can be setup inside the config file.
