### ISSUE TITLE
[SUGGESTION] Full utilization of PlayerData.job.type == "leo"

### ISSUE THREAD

**Issue by menkzy** [qbcore-framework/qb-policejob#375]
_**Is your feature request related to a problem? Please describe.**_

Currently, qb-policejob only calls for a job check if you are under the "police" job with `PlayerData.job.name == "police"` which when you want to utilize `PlayerData.job.type == "leo"` it will [throw errors ](https://i.imgur.com/18XqY3g.png). This part of code is from handling blips.

It also effects the use of qb-target, as you can only use the job = "jobname", param in qb-target and not the type.

_**Describe the feature you'd like**_

Full compatiblilty of the `job.type` function that is built into qbcore to be used in qb-policejob and other jobs such as ambulancejob

**Comment by tom-osborne** [comment]
https://github.com/qbcore-framework/qb-policejob/pull/369

**Comment by i-kulgu** [comment]
#434
