### ISSUE TITLE
cars not showing in garage 

### ISSUE THREAD

**Issue by tyler4435** [qbcore-framework/qb-policejob#377]
cars not showing in garage

**Comment by arsh939** [comment]
@tyler4435 do you get any error in console?

**Comment by Xiantyl** [comment]
Same issue no errors just says no vehicles found

**Comment by Blooper-bloop** [comment]
> Same issue no errors just says no vehicles found

Any errors and are you up to date ?

**Comment by i-kulgu** [comment]
I can't reproduce this issue with the latest policejob.
Please update your version.
