### ISSUE TITLE
[BUG] Vehicles and helicopter do not spawn

### ISSUE THREAD

**Issue by fedealomso** [qbcore-framework/qb-policejob#378]
Configured vehicles do not spawn. The list appears but does not generate the vehicle. There are no errors in the console

![image](https://user-images.githubusercontent.com/55077903/187413405-1eddccef-cdd1-443f-9ddd-5313f955b1cb.png)

**Comment by thenexsk** [comment]
In policejob/client/main.lua in function TakeOutVehicle change the callback to SpawnVehicle function

**Comment by TheProcrastiDad** [comment]
I'm having the same issues and after Making this change i do not see an improvement. still without error messages.

**Comment by kathryn2101** [comment]
i have resently set this to a a target option on a ped the menu comes up but vehicles wont spawn but if i do /car (vehiclename) the car appears it never worked before in pd till i changed it to a target option on a ped and now it doesnt work even more but all the other jobs like ambulancejob and towjob their vehicle spawns are fine and they are able to be pulled out its just the police job

you cant pull out police vehicles or police impounded vehicles

**Comment by Scones91** [comment]
No issues for me...

**Comment by Homosexual-Insomnia** [comment]
Im having the same exact issue when I try to update to the latest version.

**Comment by zwkf** [comment]
Closing this due to the age of the ticket. If it's still a problem feel free to reopen or raise another ticket. Thanks
