### ISSUE TITLE
Fleet vehicles do not spawn in with keys

### ISSUE THREAD

**Issue by ckaysone380** [qbcore-framework/qb-policejob#380]
Police cars in the fleet list is no longer spawning in with keys, having to search for keys to use vehicles, unsure if it’s related with vehicle keys or locks but I’ve updated police job, vehicle shop and vehicle keys and nothing is resolving it.

**Comment by i-kulgu** [comment]
Do you still have this issue ? There are some fixes released regarding this issue.
