### ISSUE TITLE
[BUG] On/Off Duty doesnt work correctly when you don't use Target

### ISSUE THREAD

**Issue by CptNoHand** [qbcore-framework/qb-policejob#387]
**Describe the bug**
We don't use Target atm and DrawText for the duty location shows as inteded, but you can move 10 or more meters away and when you press E und again you again toggle duty.

1. Go to duty location
2. Toggle duty
3. go few feet away till it disappears wait till notify goes away 
4. you toggle duty again, even when the drawtext isnt showing anymore

**Expected behavior**
To not toggle after drawtext disappears

**Questions (please complete the following information):**
 - When you last updated: lwhen the newest update hit
 - Are you using custom resource? which ones? a lot, but nothing toggles duty and police stuff
 - Have you renamed `qb-` to something custom? no

**Comment by singh-manavv** [comment]
Just decrease the distance of the BoxZone of duty zone .

**Comment by CptNoHand** [comment]
The problem is, even if i'm technically out of the zone, i can still toggle duty for a while.--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 11.09.22, 05:14 schrieb Manav Singh ***@***.***>:

   
  Just decrease the distance of the BoxZone of duty zone .

**Comment by singh-manavv** [comment]
Make sure the length and width of box zone is small , and distance is also like 1 or 1.5 , ypu will be good to go

**Comment by i-kulgu** [comment]
> The problem is, even if i'm technically out of the zone, i can still toggle duty for a while.

Do you still face this problem or is it solved already ?

**Comment by CptNoHand** [comment]
Still happening. I made the zone smaller, but that isn't the problem. As soon as you walk too close past it and it comes up, the next time you press "E" you toggle it.

**Comment by tom-osborne** [comment]
@CptNoHand This can be fixed by changing the following line:
https://github.com/qbcore-framework/qb-policejob/blob/main/client/job.lua#L821

From:
```lua
            inDuty = false
```
```lua
            dutylisten = false
```
I'll get a PR raised.
