### ISSUE TITLE
[BUG] handcuff myself

### ISSUE THREAD

**Issue by Luckyyang24** [qbcore-framework/qb-policejob#392]
I'm experiencing this issue where when I uses the handcuff but it only cuff myself instead of the other person?  No error on console/tdadmin either and also running the latest version of qb-core, qb-policejob, & everything.  Basically a fresh install & haven't touch the interactions.lua either.

```
RegisterNetEvent('police:client:CuffPlayerSoft', function()
    if not IsPedRagdoll(PlayerPedId()) then
        local player, distance = QBCore.Functions.GetClosestPlayer()
        if player ~= -1 and distance < 1.5 then
            local playerId = GetPlayerServerId(player)
            if not IsPedInAnyVehicle(GetPlayerPed(player)) and not IsPedInAnyVehicle(PlayerPedId()) then
                TriggerServerEvent("police:server:CuffPlayer", playerId, true)
                HandCuffAnimation()
            else
                QBCore.Functions.Notify(Lang:t("error.vehicle_cuff"), "error")
            end
        else
            QBCore.Functions.Notify(Lang:t("error.none_nearby"), "error")
        end
    else
        Wait(2000)
    end
end)
```
https://i.imgur.com/2olNVoT.png

**Comment by Luckyyang24** [comment]
So I just found out that only the handcuffs from /additem weapon_handuffs and /giveitem 1 weapon_handcuffs 1 commands are the only one having this issue.  Is there two version of handcuffs or something?  Rhe one from the command does not show any picture.  I revert back to fresh install server to test it out

https://i.imgur.com/cI1HgFe.png

**Comment by Luckyyang24** [comment]
Okay, so nvm.  I found the issue.  There's two handcuff which is  weapon_handcuffs & handcuffs in qbcore/shared/items.lua.  The weapon_handcuffs  was the one that kept cuffing myself.  Dunno if it was change it or something but the "handcuffs" one is working fine now.

**Comment by singh-manavv** [comment]
okay perfect , so i'm closing this issue as  its resolved .
