### ISSUE TITLE
Police Job

### ISSUE THREAD

**Issue by npcore-framework** [qbcore-framework/qb-policejob#4]
Good day, This will include all the functions that we've found from the police that work and do not work.

For the Police Department location ,only if you have the police job , you can unlock any areas (armory, lockers, jail) and you can start duty by going at the PC in the lobby.
If you are the Police Chief (rank 4) you can also access the boss menu, which let's you hire, promote people and also let's you deposit money for the police.
At the Police Department at the moment from what I can see the only thing that is missing is either a system for the police outfits, or adding all the police uniforms to the clothing store so we can change them there.
-The armory has weapons and police equipment inside and can be accessed by any people in the Police Department. 

Radial Work menu for Police.
-The "take license" option does not seem to work 
-From Police interaction , the jail function doesn't seem to work ,it says that it jails the person but it doesn't , I will try with higher amounts of time also) -- Jail MLO required with the appropriate event trigger.
-The Emergency button we do not know what it does
-Check tune status i do not believe it's available (it says NULL: Chiptuned:no)
-Reset house key I do not know what it does
Apart from those, the rest seem to work just fine.
-Cuffing a player, either by /cuff or using the radial menu.
-Search a player 
-Escort a player 
-You can place down several types of objects including spike strips which work

The pings for Police work, if someone is driving recklessly or shoots a weapon you receive a message in the top right of the screen with a description of the suspect and relative location. :D

![image](https://user-images.githubusercontent.com/83185289/117019733-8cb4a980-acaa-11eb-906c-0764683fb917.png)
![image](https://user-images.githubusercontent.com/83185289/117020080-f1700400-acaa-11eb-8b98-7883f5ad2935.png)

Tengri,
OGN TEAM.

**Comment by Demonith** [comment]
So it means its working

**Comment by np-core-framework** [comment]
Yes, overall qb-police operates as intended, but does require minor modifications for production use.

**Comment by GhzGarage** [comment]
Thank you for the report i will look into these

**Comment by DistinctMatriarch** [comment]
When reloading your weapon whatever ammo is loaded in REMOVES if you put your gun away and pull it out again

**Comment by npcore-framework** [comment]
> 
> 
> Thank you for the report i will look into these
Pardon the late response.
No worries! Keep up the good job.
