### ISSUE TITLE
On / Off Duty

### ISSUE THREAD

**Issue by CrypticOG** [qbcore-framework/qb-policejob#40]
Since the newest update whenever I go off-duty I am not able to go back on duty. The text disappears.

**Comment by Developer-Bear** [comment]
Any errors in either client or server console? I am not having this issue.

**Comment by nick-perry14** [comment]
^ Check for an error.  Sometimes it has to do with the fact rp-radio is not started.

**Comment by CrypticOG** [comment]
Yes it was an issue with Rp-radio! Thank you all!
