### ISSUE TITLE
[SUGGESTION] Adding on Additional Departments Under The Same Job

### ISSUE THREAD

**Issue by ckaysone380** [qbcore-framework/qb-policejob#401]
**Is your feature request related to a problem? Please describe.**
No, just a simple request to add more than one department

**Describe the feature you'd like**
Instead of setting up departments under the same police job umbrella and adding in multiple grades ranging from 0-50+, if there is a feature update coming soon to incorporate this?

**Describe alternatives you've considered**
Alternatives I done was to just add each department into the job grades but was making it difficult for bosses to keep up with who is under their departments and manage their own society funds and not tap into one.

**Comment by Irishstevie** [comment]
The team Is working on something called Job types
With the hope that you can have more then one 
department not just with police but most of the jobs 

![bitmoji](https://sdk.bitmoji.com/render/panel/2196307c-2ceb-46f8-8bf4-4c3e3f34f93e-3ca774e2-d4c1-4b43-918f-8e7b457ae163-v1.png?transparent=1&palette=1&width=246)

**Comment by i-kulgu** [comment]
> **Is your feature request related to a problem? Please describe.** No, just a simple request to add more than one department
> 
> **Describe the feature you'd like** Instead of setting up departments under the same police job umbrella and adding in multiple grades ranging from 0-50+, if there is a feature update coming soon to incorporate this?
> 
> **Describe alternatives you've considered** Alternatives I done was to just add each department into the job grades but was making it difficult for bosses to keep up with who is under their departments and manage their own society funds and not tap into one.

See #434 , it's done in there.
