### ISSUE TITLE
[BUG] Can't see duty markers.

### ISSUE THREAD

**Issue by MrWilling** [qbcore-framework/qb-policejob#407]
**Describe the bug**
When I go to the specified co-ords I can't actually see any marker to go on or off duty.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://imgur.com/a/FtsQtK1)

**Additional context**

Config.UseTarget = GetConvar('UseTarget', 'false') == 'false'
Config.Locations = {
    ["duty"] = {
        [1] = vector4(440.085, -974.924, 30.689, 90.654),
        [2] = vector4(-449.811, 6012.909, 31.815, 90.654),

**Comment by Blooper-bloop** [comment]
> **Describe the bug** When I go to the specified co-ords I can't actually see any marker to go on or off duty.
> 
> **Screenshots** [If applicable, add screenshots to help explain your problem.](https://imgur.com/a/FtsQtK1)
> 
> **Additional context**
> 
> Config.UseTarget = GetConvar('UseTarget', 'false') == 'false' Config.Locations = { ["duty"] = { [1] = vector4(440.085, -974.924, 30.689, 90.654), [2] = vector4(-449.811, 6012.909, 31.815, 90.654),

Its Vector 3 not 4 that should fix it @MrWilling
