### ISSUE TITLE
[BUG]Players Blip disappear 

### ISSUE THREAD

**Issue by Christina1734** [qbcore-framework/qb-policejob#408]
**Describe the bug**
The blips of the crew will disappear if the distance between the member and you is more than 200m or a larger distance.
**To Reproduce**
1. Simply just make the distance long enough
2. There're no error code

**Expected behavior**
It should show blip of the entity if the member was onduty and the job name is police or ambulance.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: about a week ago
 - Are you using custom resource? No
 - Have you renamed `qb-` to something custom? No

**Additional context**

**Comment by i-kulgu** [comment]
This is not a bug but a normal behavior.
Look in client\main.lua:29 : 

![image](https://user-images.githubusercontent.com/29943243/199439838-154210ef-92e4-4b95-89c4-a106d95b30eb.png)

It's setting the blip as short range.

![image](https://user-images.githubusercontent.com/29943243/199439972-cb614cf1-0722-4cd1-82f3-9b29e60f963e.png)
