### ISSUE TITLE
garage system not working [BUG]

### ISSUE THREAD

**Issue by JesseJames804** [qbcore-framework/qb-policejob#410]
So im having an issue where my PD cars show up regardless of rank in the pd garage does anyone have an idea why?

**Comment by Blooper-bloop** [comment]
> So im having an issue where my PD cars show up regardless of rank in the pd garage does anyone have an idea why?

First off what errors are you getting and are you all up to date ? @JesseJames804

**Comment by JesseJames804** [comment]
Yes all up too date and no errors at all in the system just all vehicles show up for all ranks regardless

**Comment by Txc32** [comment]
how you fix that?
