### ISSUE TITLE
[BUG] Helicopter not spawning?

### ISSUE THREAD

**Issue by 12Echo** [qbcore-framework/qb-policejob#420]
**Describe the bug**
Helicopters used to spawn fine for me, but now they're refusing to spawn. When I'm offduty the press [E] for heli comes up, but doesn't work. When I'm onduty it just doesn't appear or work at all.

**To Reproduce**
1. Try and spawn in a helicopter from one of your set spots

**Expected behavior**
Helicopter spawns

**Screenshots**
N/A

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] : Now after I started experiencing the bug
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] : None
 - Have you renamed `qb-` to something custom? [e.g. yes/no] : No

**Comment by Scones91** [comment]
Can't reproduce. Works fine for me. Both spawning and parking while on duty.
