### ISSUE TITLE
[BUG] Evidence

### ISSUE THREAD

**Issue by FurmaZ** [qbcore-framework/qb-policejob#428]
![image](https://user-images.githubusercontent.com/69918985/206485778-49a16a06-5900-4475-b926-849def31a680.png)

When trying to do /clearblood or /clearcasings Im getting this error

**Comment by i-kulgu** [comment]
This is not an error but a (debug) warning. You can ignore this.

**Comment by Z3rio** [comment]
This has to do with the progressbar, not qb-policejob
