### ISSUE TITLE
[BUG] [ script:qb-policejob] Warning: Missing phrase for key: "commands.fine"

### ISSUE THREAD

**Issue by SKITTLE6969** [qbcore-framework/qb-policejob#430]
**Describe the bug**
getting this error after updating to latest police job, is it something to worry aboout? /fine command dosen't work also. Is there any other dependency to this that I'm missing?

**Screenshots**
![image](https://user-images.githubusercontent.com/92496158/208227887-35d39b2a-0b28-450f-84c0-82b2a79083fd.png)

**Comment by Scones91** [comment]
Works for me.

**Comment by jamesR227** [comment]
How would we update it though?
