### ISSUE TITLE
Robberys mark every officer onduty

### ISSUE THREAD

**Issue by ramonvega2400** [qbcore-framework/qb-policejob#442]
When someone does a Robbery using lockpick, for example a store robbery cash register. It does the call to police and then pings each officer and makes a blip for every officer on the map. 
![image](https://user-images.githubusercontent.com/92761498/212236283-908231e6-25dc-42a0-bcc1-ab5c18cc3578.png)
![image](https://user-images.githubusercontent.com/92761498/212236289-66250771-bb98-44ea-9df6-7749d910440e.png)

**Comment by zwkf** [comment]
Is there a way you could give us more information please?

**Comment by br4ndo1** [comment]
I am having this issue right now. Any fix?
