### ISSUE TITLE
Police vehicle trunks empty

### ISSUE THREAD

**Issue by twigmasters** [qbcore-framework/qb-policejob#445]
**Describe the bug**
Just updated police job to newest version and noticed when I pull a car from the police garage it is not spawning with anything in the trunk when I can see in the config the items are there. Anyone else notice this or am I missing something?

**Comment by GodyFromDiscord** [comment]
This was due to one of the inventory updates for security, a pr has been made in place of [this](https://github.com/qbcore-framework/qb-inventory/pull/422);

**Comment by TwanLuttik** [comment]
@twigmasters you should close the issue since the pr has already merged
