### ISSUE TITLE
Disable movement

### ISSUE THREAD

**Issue by TevisHobart** [qbcore-framework/qb-policejob#468]
I want to prohibit players from walking when they are handcuffed

**Comment by AnishBplayz** [comment]
Try hardcuffing them

**Comment by TevisHobart** [comment]
> 尝试给它们戴硬铐

I used handcuffs to put players on, but they can still walk

**Comment by AnishBplayz** [comment]
Try /hc its for hardcuffs

**Comment by FortifiedGrizzly** [comment]
you could create an item, for the other handcuffs if you wish (this is what I have done) I called them "speedcuffs" Here is the function I made, I added it to qb-policejob / server / main.lua

`QBCore.Functions.CreateUseableItem("speedcuffs", function(source, item)
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    if Player.Functions.GetItemByName(item.name) then
        TriggerClientEvent("police:client:CuffPlayer", src)
    end
end)`
