### ISSUE TITLE
[BUG] Impound not working

### ISSUE THREAD

**Issue by Frankieg92** [qbcore-framework/qb-policejob#470]
Getting this issue when trying to open police impound 
![image_2023-06-01_171834142](https://github.com/qbcore-framework/qb-policejob/assets/131482478/cb8ee0c7-2e41-4b76-ab29-10c0015f2c0e)

**Comment by wasuryanto3** [comment]
same

**Comment by rxnm** [comment]
How exactly are you trying to impound? it is working fine for me.

**Comment by Henkw00** [comment]
> How exactly are you trying to impound? with what such command I mean, cause it is working fine for me.

i got the same issue, highest rank of police but cant impound: "for on-duty police only"
also appears when tring to /jail someone
