### ISSUE TITLE
[BUG] Police Marker

### ISSUE THREAD

**Issue by DanielWolf-nw** [qbcore-framework/qb-policejob#471]
The bug:

I have the bug that when I give myself the police job or get it, I don't see the markers on the map, e.g. the marker in the changing room or the police garage

What I expected:

I expected there to be a marker for it

**Comment by DanielWolf-nw** [comment]
As for the update, I use the QB version of Zaphosting without tx. I was told that it was always the current Github version

**Comment by qb-core-dutch** [comment]
policejob has no markings

**Comment by jimjim135** [comment]
I can second this issue from what I can tell on my server.

**Comment by rxnm** [comment]
You don't get markers for the changing room or garage, what are you on about? lol. You also don't see your own blip when police, but you will see others if they are in the police and on duty.
