### ISSUE TITLE
[BUG]Amory is not showing what its supposed to

### ISSUE THREAD

**Issue by EddieMLG7** [qbcore-framework/qb-policejob#473]
**Describe the bug**
I have added to the armory through the config file and added more to the different stations, but every time i open it, it shows nothing but the name

**Expected behavior**
Open armory and have the things you have added show up.

**Screenshots**
![Screenshot (3)](https://github.com/qbcore-framework/qb-policejob/assets/47540619/19b34f7b-5085-4d17-b9fb-8068289d0686)
**Questions (please complete the following information):**
 - When you last updated: no clue
 - Are you using custom resource? which ones?
 just qb-policejob 

 - Have you renamed `qb-` to something custom? no

**Comment by rxnm** [comment]
This is not a bug, you have obviously messed up somewhere by adding more items. I bet if you removed your config and used a clean config it would work fine. Post your script here so I can take a look at it, please.
