### ISSUE TITLE
[BUG] Evidence Stashes Do Not Open

### ISSUE THREAD

**Issue by ThatGivensGuy** [qbcore-framework/qb-policejob#487]
**Describe the bug**
Trying to open an evidence stash doesn't work. When you go to the marker, if qb-target is enabled, nothing pops up. If it's disabled, the "Evidence Stash | " pops up on the left side of the screen but only shows the incomplete %{value} next to it. It doesn't open the input menu to allow you to choose a stash.

**To Reproduce**
1. Go to your evidence locations
2. Try and interact with it
3. Fail

**This Is on The Newest Version of QB-PoliceJob**

**Comment by Nophobia09** [comment]
Crazy.... but I found that the call is not accurate. Check at or around line 614 or just Control +F and search function evidence() and compare to what I have below. Im still working throught this to not disable nui mouse when opening the evidence but that might not happen for you. I have an aftermarket inventory which may be the issue for the loss of mouse control. Update me here if it works as expected once you change the Function call on line 623 qb-policejob > client > job.lua
```lua
-- Evidence Thread
local function evidence()
    CreateThread(function()
        while true do
            Wait(0)
            if inEvidence and PlayerJob.type == 'leo' then
                if PlayerJob.onduty then sleep = 5 end
                if IsControlJustReleased(0, 38) then
                    print('opened')
                    --TriggerEvent('qb-policejob:client:EvidenceStashDrawer')
                    TriggerEvent('police:client:EvidenceStashDrawer')
                    break
                end
            else
                break
            end
        end
    end)
end
```

**Comment by adtgamer** [comment]
nothing happened here

**Comment by Nophobia09** [comment]
Message me on discord, I'll hop in a channel and help. 

n0phobia

**Comment by Nophobia09** [comment]
> nothing happened here


Message me on discord, I'll hop in a channel and help.

n0phobia

**Comment by adtgamer** [comment]
I don't speak English, I use Google Translate, I'm from Brazil

**Comment by djgetti** [comment]
> **Describe the bug** Trying to open an evidence stash doesn't work. When you go to the marker, if qb-target is enabled, nothing pops up. If it's disabled, the "Evidence Stash | " pops up on the left side of the screen but only shows the incomplete %{value} next to it. It doesn't open the input menu to allow you to choose a stash.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to your evidence locations
> 2. Try and interact with it
> 3. Fail
> 
> **This Is on The Newest Version of QB-PoliceJob**

Mine is doing exact same thing

**Comment by Nophobia09** [comment]
> > **Describe the bug** Trying to open an evidence stash doesn't work. When you go to the marker, if qb-target is enabled, nothing pops up. If it's disabled, the "Evidence Stash | " pops up on the left side of the screen but only shows the incomplete %{value} next to it. It doesn't open the input menu to allow you to choose a stash.
> > 
> > **To Reproduce** Steps to reproduce the behavior:
> > 
> > 1. Go to your evidence locations
> > 2. Try and interact with it
> > 3. Fail
> > 
> > **This Is on The Newest Version of QB-PoliceJob**
> 
> Mine is doing exact same thing
> 
> ![image](https://github.com/qbcore-framework/qb-policejob/assets/83934881/71fa0c52-ddac-41b7-b54b-d1885450f38e)
> 

If you change what I put up above, and have target off it will work. If you want target on you'll also have to change it somewhere else in the code. I'm not at my PC or I'd send the line.

**Comment by djgetti** [comment]
yea that would be great if you could find what line that would be to keep it as qb-target true.. Thank you

**Comment by Nophobia09** [comment]
> yea that would be great if you could find what line that would be to keep it as qb-target true.. Thank you.
> Yes it works but we still see 'Evedence Stash | %{value} so by going qb-target that wouldnt be there
> 

I'm still away from my PC, but looking at my phone it looks to be line 801, change the event being triggered FROM 'qb-policejob:client:EvidenceStashDrawer' TO 'police:client:EvidenceStashDrawer' lmk if that helps

**Comment by Nophobia09** [comment]
> I just tested the last line you commented that could help and I put it in and the text is still staying the same but the stash itself works normally. https://imgur.com/a/0v36xhJ
@ChochoZagorski 
@djgetti 
If you want it to say Evidence Stash | [E] then simply copy this and paste it into your locales lua. For example, I use en.lua for my locale as I am in an english speaking server. So I would change line 87 from         
```lua
evidence_stash = 'Evidence Stash | %{value}',
```
TO
```lua
        evidence_stash = 'Evidence Stash | [E]',
```

Otherwise I would need to see more info on how you have the evidence locations listed in the config as well as any modifications made in policejob to determine why its not displaying the accurate evidence number for that specific location. Hope this helps!

**Comment by KrvarGG** [comment]
Thanks you have fixed this issue for me very thankful someone could help me figure out this issue <3

**Comment by Permmm** [comment]
I did the steps but it isnt working with target for some reason. any help?

**Comment by Nophobia09** [comment]
> I did the steps but it isnt working with target for some reason. any help? 

I will post the updated version I have and you can use it. I'm away from my PC ATM tho. I'll do it tonight.

**Comment by Permmm** [comment]
@Nophobia09 Did you have the new version available?

**Comment by ThatGivensGuy** [comment]
> ```lua
> qb-policejob:client:EvidenceStashDrawer
> ```

Alright, so, now we can open the stashes.. but now you can't interact w/ them. The stash opens and it doesn't give you your mouse to move. X-x

**Comment by JustTobii** [comment]
Only add this to your qb-policejob/server/main.lua and you are done. :)

```
RegisterNetEvent('qb-policejob:server:evidence', function(currentEvidence)
    local src = source
    local Player = QBCore.Functions.GetPlayer(src)
    if not Player then return end
    if Player.PlayerData.job.type ~= 'leo' then return end
    exports['qb-inventory']:OpenInventory(src, currentEvidence, {
        maxweight = 4000000,
        slots = 500,
    })
end)
```
