### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RLJB1** [qbcore-framework/qb-policejob#493]
When Trying To Move The Evidence Vectors The Evidence Does Not work? Have been Trying For Months To Sort This Issue?

**Comment by kaynegraham** [comment]
Are you using the correct coords, please show some code?

**Comment by Hatchet1311** [comment]
I am having the same issue 
![image](https://github.com/qbcore-framework/qb-policejob/assets/100534700/844141ad-7490-4d29-a16b-3d4f960c253c)

**Comment by kaynegraham** [comment]
@Hatchet1311 Is there any errors, possibly try a vector4 instead?

**Comment by Hatchet1311** [comment]
I actually went back through commits and realized my issue was there it was mostly job lua changing qb-policejob to police ... cheers for getting back though
