### ISSUE TITLE
[BUG] duty issue

### ISSUE THREAD

**Issue by NotPhelps** [qbcore-framework/qb-policejob#496]
**Describe the bug**
i have a fresh install of qbcore recipe nothing change/added at all if im on duty when i f8 quit someone can still rob a store its weird cuase no errors at all

**To Reproduce**
go on duty as a cop/ems or any job that uses duty

have a player rob the store after you are on duty and you have f8 quit without going off duty

they will still be able to rob the place with no cops on duty 

and agian i havent touched the files at all so it shouldnt be like this 

**Expected behavior**
should be able to f8 quit and the job dectect youve logged off so people cant just rob the store when the cops log off or crash like it use to be that way idk if its just a bug or not

**Screenshots**
n/a

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]  today 
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] nope
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**

**Comment by Pewwww53** [comment]
This is not an issue in this resource

**Comment by GhzGarage** [comment]
I'll check where it updates the cop count, thanks

**Comment by GhzGarage** [comment]
Also, which robbery specifically?

**Comment by NotPhelps** [comment]
> Also, which robbery specifically?

its any thing that requires the count but the one i tested the most was store robbery

**Comment by damainman11** [comment]
Having the same issue here. Updated qb-policejob and now count is not updating

**Comment by NotPhelps** [comment]
any updates?

**Comment by damainman11** [comment]
> any updates?

I have fixed the issues with policejob which can be found here. https://github.com/damainman11/qb-policejob

**Comment by NotPhelps** [comment]
> > any updates?
> 
> I have fixed the issues with policejob which can be found here. https://github.com/damainman11/qb-policejob

nothing in it?
