### ISSUE TITLE
[BUG] - Client/Heli.lua:141: Attempt to index a nil value (global 'PlayerJob')

### ISSUE THREAD

**Issue by ChlxeThomson** [qbcore-framework/qb-policejob#497]
**Describe the bug**
Fresh install of the latest version, suddenly get F8 error. I'm using latest QBCore framework (less than 3 weeks old) and my job for Police is called 'Police'

**Expected behavior**
for the script to work with no errors

**Screenshots**
<img width="1011" alt="Screenshot 2024-01-29 192223" src="https://github.com/qbcore-framework/qb-policejob/assets/58238399/19de1a4c-66ed-4688-b2d6-3cf273cf556c">
<img width="452" alt="Screenshot 2024-01-29 192232" src="https://github.com/qbcore-framework/qb-policejob/assets/58238399/ea5fa902-9d4d-45ea-a76e-e66904e083c0">

**Questions (please complete the following information):**
 - When you last updated: Today 29th Feb 2024
 - Are you using custom resource? No
 - Have you renamed `qb-` to something custom? No

**Additional context**
Would like help please

**Comment by Pewwww53** [comment]
probably the PlayerJob variable is undefined can send the whole script?

**Comment by ChlxeThomson** [comment]
> probably the PlayerJob variable is undefined can send the whole script?

How can i send it you, whats your Discord, i'll send it that way

**Comment by Pewwww53** [comment]
Pewww#0001

**Comment by ChlxeThomson** [comment]
> Pewww#0001

Added you, send me message when you got me

**Comment by goldeneyegsm** [comment]
Please let us know when fixed

**Comment by GhzGarage** [comment]
@ChlxeThomson Did this issue get resolved?

**Comment by goldeneyegsm** [comment]
yes. thank you

**Comment by ChlxeThomson** [comment]
> @ChlxeThomson Did this issue get resolved?
> 

Yes it's now been fixed, thank you

**Comment by ChlxeThomson** [comment]
> @ChlxeThomson Did this issue get resolved?
> 

Yes it now fixed thank you
