### ISSUE TITLE
Bug dupe item proof box

### ISSUE THREAD

**Issue by nylanpro** [qbcore-framework/qb-policejob#50]
Hello, there is an error in the proof box, creating many items in the same series!
Video error: https://streamable.com/y1367x
Thanks

**Comment by Developer-Bear** [comment]
unable to repro: https://streamable.com/w08v7u

Please make sure you have the latest version and retest

**Comment by nylanpro** [comment]
yes, I have updated to the latest version now, I just downloaded and updated again, still getting the same error

**Comment by GhzGarage** [comment]
qb-inventory handles the stash logic not the policejob

**Comment by nylanpro** [comment]
I think so too, I also update qb-Inventory but I still get the same error, because I always use the latest update
