### ISSUE TITLE
[SUGGESTION] Make vehicles purchaseable and storeable in qb-garages

### ISSUE THREAD

**Issue by danile666** [qbcore-framework/qb-policejob#52]
Make police vehicles purchasable

Make police vehicles storable in normal garages.

**Comment by flip4fzL** [comment]
You can already do that.
Add a police vehicle to shared.lua, add it to a sub-category in your vehicleshop.
Purchase the vehicle and store it in garage like other players.

**Comment by danile666** [comment]
> You can already do that.
> Add a police vehicle to shared.lua, add it to a sub-category in your vehicleshop.
> Purchase the vehicle and store it in garage like other players.

Right, but I am looking to whitelist it only to police, and have the garage and shop for police vehicles only accessible to police with only police vehicles in it.  That way it is a cleaner solution and random people are not pulling cars from the police dept.  Or pulling cop cars from normal garages or shops.  

If whitelisting cop cars under the qb-vehicleshop script and whitelisting specific garages to cops is built in by all means lead me to the light.  I havent been able to figure it out.

**Comment by ihyajb** [comment]
also please add [SUGGESTION] in your title so this can get moves to suggestions and not issues. Thank you!

**Comment by Maverick167** [comment]
> > You can already do that.
> > Add a police vehicle to shared.lua, add it to a sub-category in your vehicleshop.
> > Purchase the vehicle and store it in garage like other players.
> 
> Right, but I am looking to whitelist it only to police, and have the garage and shop for police vehicles only accessible to police with only police vehicles in it. That way it is a cleaner solution and random people are not pulling cars from the police dept. Or pulling cop cars from normal garages or shops.
> 
> If whitelisting cop cars under the qb-vehicleshop script and whitelisting specific garages to cops is built in by all means lead me to the light. I havent been able to figure it out.

I think you can already do that by just creating a new shop in qb-vehicleshop. Create a new shop, set the "OwnedJob" variable in the config to "police", then place the coordinates near the PD somewhere like inside the basement-level garage. Add the police vehicles to shared.lua and assign them to the new shop. That should make them only accessible to police.

**Comment by danile666** [comment]
> > > You can already do that.
> > > Add a police vehicle to shared.lua, add it to a sub-category in your vehicleshop.
> > > Purchase the vehicle and store it in garage like other players.
> > 
> > 
> > Right, but I am looking to whitelist it only to police, and have the garage and shop for police vehicles only accessible to police with only police vehicles in it. That way it is a cleaner solution and random people are not pulling cars from the police dept. Or pulling cop cars from normal garages or shops.
> > If whitelisting cop cars under the qb-vehicleshop script and whitelisting specific garages to cops is built in by all means lead me to the light. I havent been able to figure it out.
> 
> I think you can already do that by just creating a new shop in qb-vehicleshop. Create a new shop, set the "OwnedJob" variable in the config to "police", then place the coordinates near the PD somewhere like inside the basement-level garage. Add the police vehicles to shared.lua and assign them to the new shop. That should make them only accessible to police.

I will try this out, but it does seem that Owned Job expects the vehicle to be returned to the shop, as in the owner isnt really the owner/purchasing it.  I will try and see what we are dealing with, but if that is the case it is not what im looking for.  I am really looking for purchaseable cars.

**Comment by phumberdroz** [comment]
I believe what you are looking for is the functionality from GangGarages of the qb-garages package. 

There is currently an open mr here: https://github.com/qbcore-framework/qb-garages/pull/29

**Comment by danile666** [comment]
So I wound up editing qb-vehicleshop and have it working.  I have some commands that exclude police and ambulance jobs from the sell command.  I then added a buy command for those two jobs.  Ran into an issue with the police vehicles not deleting, but managed to implement rayhandle and getvehicleindirection.  

So I have the functionality through a different script after updating it
