### ISSUE TITLE
/jail not working

### ISSUE THREAD

**Issue by meistroburger** [qbcore-framework/qb-policejob#6]
If you put in /jail ID TIME it only gives a notification, and not send the person to jail

**Comment by Manliketjb** [comment]
Need a prison dependency like on the kash Qbus files - https://github.com/KASH4/qbus/tree/main/resources/%5Bstandalone%5D/prison

**Comment by GhzGarage** [comment]
Try this and lmk if it works for you https://github.com/qbcore-framework/qb-prison

**Comment by Manliketjb** [comment]
> Try this and lmk if it works for you https://github.com/qbcore-framework/qb-prison

Does work. its exactly the same than the one I'm currently using
