### ISSUE TITLE
[BUG] Default Items show up broken 

### ISSUE THREAD

**Issue by phumberdroz** [qbcore-framework/qb-policejob#75]
![image](https://user-images.githubusercontent.com/3389721/130306679-d5898651-4cf4-4d7a-9955-ae26b46cd7ac.png)

**Comment by avery1227** [comment]
Can confirm this is an issue.

https://files.cadojrp.com/Drab-Arcticfox-Monstrous-Anteater.png
https://files.cadojrp.com/Ringed-Trumpeterswan-Fortunate-Littlenightmonkeys.png

**Comment by avery1227** [comment]
Just pushed a PR to fix this: #76
