### ISSUE TITLE
Police Grades

### ISSUE THREAD

**Issue by Ericrosa09** [qbcore-framework/qb-policejob#98]
I have looked through the majority of files and am trying to figure out how to add more police grades.

I hope I can get some help from you.

**Comment by papabendi** [comment]
Check your qb-core/shared.lua

**Comment by Ericrosa09** [comment]
Worked perfectly, thanks for helping me out.

**Comment by Xarasks** [comment]
could someone help me code out more ranks aswell for these ranks?
Probationary Police officer
Police Officer I
Police Officer II
Senior Police Officer 
Corporal
Sergeant
Lieutenant
Captain
Inspector 
Commander
Detective
Cheif
